### ISSUE TITLE
Error while creating environment

### ISSUE THREAD

**Issue by batxes** [zeyang-shen/maggie#2]
Hi, 

when running 

`conda env create --file environment.yml
`

I go the following error:

```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement glob3 (from logomaker)
ERROR: No matching distribution found for glob3

failed

CondaEnvException: Pip failed
```
Most of the libraries are installed but this one failed. Is this something I need to fix on my side or is an issue of the environment?

thanks!

**Comment by zeyang-shen** [comment]
Hi, 

Sorry for the delayed response, but I believe the error you saw before during installation has now been fixed. 

The issue was caused by outdated "logomaker" package dependency (https://pypi.org/project/logomaker/). It used to be version 0.7 and is now updated to 0.8 in the "environment.yml" file. 

Hope this will solve your problem. We appreciate you giving our github repo a try and welcome any future posts here to help us improve our package!
